config/routes.rb
Rails.application.routes.draw do

  root 'app_pages#home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, except: [:destroy]
  resources :orders, except:[:edit, :update]
  resources :drivers, except: [:destroy]

  get '/users/:id/topup', to: 'users#topup', as: 'user_topup'
  get '/drivers/:id/setlocation', to: 'drivers#setlocation', as: 'driver_setlocation'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :orders

  validates :username, :email, presence: true, uniqueness: true
  validates :email, format: {
    with: /.+@.+\..+/i,
    message: 'must be in valid email format'
  }
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 8 }, allow_blank: true
  validates :gopay, numericality: { greater_than_or_equal_to: 0.0 }

  def self.update_gopay_from_order(order)
    User.find(order.user_id).update(gopay: order.reduce_gopay)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :topup]
  skip_before_action :authorize, only: [:new, :create]

  def index
    @user = User.find(session[:user_id])
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def topup
    
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User was successfully created" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if !params[:user][:gopay].nil?
        if params[:user][:gopay].to_i != 0 && !params[:user][:gopay].match(/[^0-9]/)
          params[:user][:gopay] = params[:user][:gopay].to_i + @user.gopay
        end
        if @user.update(gopay_params)
          format.html { redirect_to users_url, notice: 'user was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :topup }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.update(user_params)
          format.html { redirect_to users_url, notive: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }

        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def gopay_params
      params.require(:user).permit(:gopay)
    end

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Create My Account</legend>

    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, size: 40 %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, size: 40 %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, size: 40 %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, 'Confirm:' %>
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Gopay Credit:</strong>
  <%= @user.gopay %>
</p>


<br/>

<%= link_to 'Edit Profile', edit_user_path(@user), :class => "btn btn-success btn-xs" %> |
<%= link_to 'Top Up', user_topup_path(@user), :class => "btn btn-success btn-xs" %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Gopay Credit:</strong>
  <%= @user.gopay %>
</p>

app/views/users/topup.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend>Enter User Detail</legend>
  <div class="field">
    Username: <%= @user.username %>
  <div class="field">
    <%= form.label :gopay %>
    <%= form.text_field :gopay, value: nil %>
  </div>

  <div class="actions">
    <%= form.submit "TOP UP" %>
  </div>
  </fieldset>
<% end %>