config/routes.rb
Rails.application.routes.draw do

  root 'app_pages#home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, except: [:destroy]
  resources :orders, except:[:edit, :update]
  resources :drivers, except: [:destroy]

  get '/users/:id/topup', to: 'users#topup', as: 'user_topup'
  get '/drivers/:id/setlocation', to: 'drivers#setlocation', as: 'driver_setlocation'

end

app/models/driver.rb
class Driver < ApplicationRecord
  has_secure_password
  has_many :orders

  geocoded_by :location
  after_validation :geocode, if: ->(obj){ obj.location.present? and obj.location_changed? }


  enum vehicle_type: {
    "Go-Bike" => 0,
    "Go-Car" => 1
  }

  validates :username, :email, presence: true, uniqueness: true
  validates :vehicle_type, presence: true, inclusion: vehicle_types.keys
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 8 }, allow_blank: true

  def self.update_gopay_driver_from_order(order)
    Driver.find(order.driver_near_first).update(gopay: order.increase_gopay)
  end

  def self.update_location_from_order(order)
    Driver.find(order.driver_near_first).update(location: order.change_driver_location )
  end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy, :setlocation]
  skip_before_action :authorize, only: [:new, :create]

  def index
    @driver = Driver.find(session[:driver_id])
  end
  
  def show
  end

  def new
    @driver = Driver.new
  end

  def edit
  end

  def setlocation
  end

  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to drivers_url, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if !params[:driver][:location].nil?
        # @driver.location = @driver.location

        if @driver.update(driver_location_params)
          format.html { redirect_to drivers_url, notice: 'Location was successfully updated.' }
          format.json { render :show, status: :ok, location: @driver }
        else
          format.html { render :setlocation }
          format.json { render json: @driver.errors, status: :unprocessable_entity }
        end

      else
        if @driver.update(driver_params)
          format.html { redirect_to drivers_url, notice: 'Driver was successfully updated.' }
          format.json { render :show, status: :ok, location: @driver }
          @drivers = Driver.all
        else
          format.html { render :edit }
          format.json { render json: @driver.errors, status: :unprocessable_entity }
        end
      end

      
    end
  end
  
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_driver
    @driver = Driver.find(params[:id])
  end

  def driver_location_params
    params.require(:driver).permit(:location)
  end

  def driver_params
    params.require(:driver).permit(:username, :email, :vehicle_type, :password, :password_confirmation)
  end
end

app/views/drivers/_form.html.erb
<%= form_for(driver) do |f| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Enter Driver Details</legend>

    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, size: 40 %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, size: 40 %>
    </div>

    <div class="form-group">
      <%= f.label :vehicle_type %>
      <%= f.select :vehicle_type, Driver.vehicle_types.keys, prompt:"Select Vehicle Type", size:40 %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, size: 40 %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, 'Confirm:' %>
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @driver.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @driver.vehicle_type %>
</p>

<p>
  <strong>Gopay Balance:</strong>
  <%= @driver.gopay %>
</p>

<p>
  <strong>Location:</strong>
  <%= @driver.location %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @driver.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @driver.latitude %>
</p>

<p>
  <strong>Number of received orders: </strong>
  <%= @driver.order_ids.count %>
</p>

<br />
<%= link_to 'Edit Profile', edit_driver_path(@driver), :class => "btn btn-success btn-xs" %> 

<%= link_to 'Set Location', driver_setlocation_path(@driver), :class => "btn btn-success btn-xs" %>

app/views/drivers/new.html.erb
<%= render 'form', driver: @driver %>

app/views/drivers/setlocation.html.erb
<%= form_with(model: @driver, local: true) do |form| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <fieldset>
    <legend>Enter Driver Detail</legend>
  <div class="field">
    Username: <%= @driver.username %>
  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, value: nil %>
  </div>

  <div class="actions">
    <%= form.submit "Set Location" %>
  </div>
  </fieldset>
<% end %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @driver.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @driver.vehicle_type %>
</p>

<p>
  <strong>Gopay Balance:</strong>
  <%= @driver.gopay %>
</p>

<p>
  <strong>Location:</strong>
  <%= @driver.location %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @driver.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @driver.latitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @driver.order_ids.count %>
</p>

<%= link_to 'Edit Profile', edit_driver_path(@driver) %> |