config/routes.rb
Rails.application.routes.draw do

  root 'app_pages#home'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users, except: [:destroy]
  resources :orders, except:[:edit, :update]
  resources :drivers, except: [:destroy]

  get '/users/:id/topup', to: 'users#topup', as: 'user_topup'
  get '/drivers/:id/setlocation', to: 'drivers#setlocation', as: 'driver_setlocation'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FINAL PROJECT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div id="banner">
      <%= image_tag 'gojek2.png', alt: "Simplified Go-Jek" %>
      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        
        <ul><li><%= link_to 'Home', root_path %></li></ul>

        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', new_order_path %></li>
            <br/>
            <li><%= link_to 'Customer Account', users_path(id: session[:user_id]) %></li>
            <li><%= link_to 'Customer History', orders_path %></li>
            <li>&nbsp;</li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
          
        <% elsif session[:driver_id] %>
          <ul>
   
            <li><%= link_to 'Driver Account', drivers_path(id: session[:driver_id]) %></li>
            <li><%= link_to 'Driver History', orders_path(id: session[:driver_id]) %></li>
            <li>&nbsp;</li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>

          <% else %>
          <ul><li><%= link_to 'Login', login_path %></li></ul>
          <br />
          <p>New member? </p>
          <ul><li><%= link_to 'Sign Up Customer', new_user_path %></li></ul>
          <ul><li><%= link_to 'Sign Up Driver', new_driver_path %></li></ul>

        <% end %>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>